# TTS server defaults
export FIRST_CHUNK_WORDS=${FIRST_CHUNK_WORDS:-40}
export NEXT_CHUNK_WORDS=${NEXT_CHUNK_WORDS:-140}
export MIN_TAIL_WORDS=${MIN_TAIL_WORDS:-12}
export SNAC_TORCH_COMPILE=${SNAC_TORCH_COMPILE:-0}
export SNAC_MAX_BATCH=${SNAC_MAX_BATCH:-64}
export SNAC_BATCH_TIMEOUT_MS=${SNAC_BATCH_TIMEOUT_MS:-10}
export ORPHEUS_MAX_TOKENS=${ORPHEUS_MAX_TOKENS:-2048}

# vLLM A100-friendly defaults (overridable via .env)
export VLLM_DTYPE=${VLLM_DTYPE:-bfloat16}
export VLLM_MAX_MODEL_LEN=${VLLM_MAX_MODEL_LEN:-2048}
export VLLM_GPU_UTIL=${VLLM_GPU_UTIL:-0.90}
export VLLM_MAX_SEQS=${VLLM_MAX_SEQS:-24}
export VLLM_MAX_BATCHED_TOKENS=${VLLM_MAX_BATCHED_TOKENS:-2048}
export VLLM_PREFIX_CACHE=${VLLM_PREFIX_CACHE:-1}
export VLLM_ENFORCE_EAGER=${VLLM_ENFORCE_EAGER:-0}
export VLLM_SWAP_SPACE_GB=${VLLM_SWAP_SPACE_GB:-4}
export VLLM_DISABLE_CUSTOM_ALL_REDUCE=${VLLM_DISABLE_CUSTOM_ALL_REDUCE:-0}
export TENSOR_PARALLEL_SIZE=${TENSOR_PARALLEL_SIZE:-1}

