# TTS server defaults
export SNAC_TORCH_COMPILE=${SNAC_TORCH_COMPILE:-0}
export SNAC_MAX_BATCH=${SNAC_MAX_BATCH:-64}
export SNAC_BATCH_TIMEOUT_MS=${SNAC_BATCH_TIMEOUT_MS:-2}
export SNAC_GLOBAL_SYNC=${SNAC_GLOBAL_SYNC:-1}
export ORPHEUS_MAX_TOKENS=${ORPHEUS_MAX_TOKENS:-1024}
