# TTS server defaults
export FIRST_CHUNK_WORDS=${FIRST_CHUNK_WORDS:-40}
export NEXT_CHUNK_WORDS=${NEXT_CHUNK_WORDS:-140}
export MIN_TAIL_WORDS=${MIN_TAIL_WORDS:-12}
export SNAC_TORCH_COMPILE=${SNAC_TORCH_COMPILE:-0}
export SNAC_MAX_BATCH=${SNAC_MAX_BATCH:-64}
export SNAC_BATCH_TIMEOUT_MS=${SNAC_BATCH_TIMEOUT_MS:-10}
export ORPHEUS_MAX_TOKENS=${ORPHEUS_MAX_TOKENS:-2048}


