# vLLM-related defaults
export VLLM_DTYPE=${VLLM_DTYPE:-float16}
export VLLM_MAX_MODEL_LEN=${VLLM_MAX_MODEL_LEN:-3072}
export VLLM_GPU_UTIL=${VLLM_GPU_UTIL:-0.95}
export VLLM_MAX_SEQS=${VLLM_MAX_SEQS:-24}
export VLLM_PREFIX_CACHE=${VLLM_PREFIX_CACHE:-1}
export VLLM_WORKER_MULTIPROC_METHOD=${VLLM_WORKER_MULTIPROC_METHOD:-spawn}
export VLLM_TORCH_COMPILE=${VLLM_TORCH_COMPILE:-0}
export TORCH_COMPILE_DISABLE=${TORCH_COMPILE_DISABLE:-1}
export TRITON_DISABLE_COMPILATION=${TRITON_DISABLE_COMPILATION:-1}


