# =============================================================================
# Docker Compose Configuration for Orpheus 3B TTS
# =============================================================================
# Alternative deployment method using docker-compose for easier management.
#
# Usage:
#   export DOCKER_IMAGE="your_username/orpheus-3b-tts:latest"
#   docker-compose -f docker/docker-compose.yml up -d
# =============================================================================

version: '3.8'

services:
  orpheus-tts:
    image: ${DOCKER_IMAGE:-orpheus-3b-tts:latest}
    container_name: orpheus-tts-server
    restart: unless-stopped
    
    # GPU configuration
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    
    # Port mapping
    ports:
      - "${HOST_PORT:-8000}:8000"
    
    # Resource limits
    shm_size: 2g
    ulimits:
      memlock: -1
      stack: 67108864
    
    # Environment variables
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - HOST=0.0.0.0
      - PORT=8000
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# Optional: Add monitoring services
# networks:
#   tts-network:
#     driver: bridge

# volumes:
#   tts-logs:
#     driver: local
